name: Build

on: [push, pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Build
      run: |
        dotnet build -c=Release
    - name: Upload
    - uses: actions/upload-artifact@v3
      with:
        name: Publish Output
        path: ./HKTool/bin/Publish
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ./HKTool/bin/Publish/SHA.txt
        files: |
          ./HKTool/bin/Publish/HKTool2.zip

